### ISSUE TITLE
Deposit error,  Type error: Return value of Bavix\WalletVacuum\Store::setBalance() must be of the type boolean, null returned

### ISSUE THREAD

**Issue by CreationLee** [bavix/laravel-wallet-vacuum#2]
Hey, it's me again,
after i intstalled bavix/laravel-wallet-vacuum:0.0.1,
there are problems occured to the depositFloat action.

**Comment by rez1dent3** [comment]
@CreationLee 
Hey. You have a cache problem. No data is written to the cache

**Comment by CreationLee** [comment]
@rez1dent3 
I tried Cache::put('key', 'value', $minutes) in my development environment, it also returned null, but  the cached really stored,
my cache driver is redis.

**Comment by CreationLee** [comment]
@rez1dent3 The Cache:add(); method will return a bool value, the Cache::put() seems not

**Comment by rez1dent3** [comment]
@CreationLee 
Then you have no options. Inherit service.
```php
use Bavix\WalletVacuum\Store;

class MyStore implements Store
{
    public function setBalance($object, int $amount): bool
    {
        parent::setBalance($object, $amount);
        return true;
    }
}
```

Service overload.
```php
    // AppServiceProvider
    public function boot(): void
    {
         ....
        $this->app->singleton(Storable::class, MyStore::class);
    }
```

After simple manipulations, the library will work for you.

**Comment by rez1dent3** [comment]
![Screenshot from 2020-07-11 11-23-39](https://user-images.githubusercontent.com/5111255/87220001-002aaa80-c369-11ea-89f7-1d633d4d526e.png)

**Comment by CreationLee** [comment]
![55fb40121539a7d3b2fc0f8d7fcba7a](https://user-images.githubusercontent.com/22748068/87220061-57457500-c393-11ea-89b3-26b2738abdbb.png)

**Comment by CreationLee** [comment]
> @CreationLee
> Then you have no options. Inherit service.
> 
> ```
> use Bavix\WalletVacuum\Store;
> 
> class MyStore implements Store
> {
>     public function setBalance($object, int $amount): bool
>     {
>         parent::setBalance($object, $amount);
>         return true;
>     }
> }
> ```
> 
> Service overload.
> 
> ```
>     // AppServiceProvider
>     public function boot(): void
>     {
>          ....
>         $this->app->singleton(Storable::class, MyStore::class);
>     }
> ```
> 
> After simple manipulations, the library will work for you.


`use Bavix\WalletVacuum\Store;

class MyStore **implements** Store //there shuold extends
{
    public function setBalance($object, int $amount): bool
    {
        parent::setBalance($object, $amount);
        return true;
    }
}`

**Comment by rez1dent3** [comment]
> class MyStore implements Store //there shuold extends

@CreationLee right, typed code in github

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
