### ISSUE TITLE
HasWalletFloat + Vaccum issue

### ISSUE THREAD

**Issue by nikuscs** [bavix/laravel-wallet-vacuum#5]
Seems like there is an issue while using HasWalletFloat with Vacuum. 

I believe the error is within the "incBalance" when it tries to increment a non-integer value. 

Can you please confirm if im doing something wrong or this is actually a bug?

Thanks for the package and keep up the great work!

Throws : 
`
ERR value is not an integer or out of range
`

- Laravel 8.0
- PRedis Client - ^1.1.6
- Redis 3.2.9
- Latest Versions of the Package

Reproduce steps : 
- Install a fresh Laravel Install
- Install your Package
- Use Predis as driver
- Enable Cache driver to Redis on wallet.php config
- Decimals set to 6

use little snippet to test it out 

`
$user = User::whereId(1)->first();
$balance = $user->wallet->depositFloat(100.0);
dd($balance);
`

**Comment by rez1dent3** [comment]
@igerslike Hey. In theory, this should not be. I'll try to reproduce it.

**Comment by nikuscs** [comment]
@rez1dent3 thanks for the quick reply, just updated with more details.

**Comment by rez1dent3** [comment]
@igerslike I checked that before the 6.x version of redis, the tags on which the new version of the library is based do not work normally. Unfortunately, you need to update redis to 6.x.

I ran all redis versions up to 6.x with docker, no result. At the moment, I will not look for a solution to support old versions. If you have a desire, then please do it.

**Comment by nikuscs** [comment]
Thanks a lot for the input, as i see Laravel Provides a method to check if tags are actually supported threw "**Cache::supportsTags()**" which could possible be used to throw a more/better execption for this case.

I understand why you have done it so you can quickly clear/flush all the balance keys with a single method. If you are comfortable i can try PR a solution to make it cross compatible with Redis 5.x ( I made a mistake on the issue i am actually using 5.3.2  ) and most of Laravel Forge Servers as i see as provisioned with 5.3.2RC1 ( at least past week ) , so i think it could be a good use to at least support version 5.x since 6.0 is pretty recent and could put some users away from trying /using this plugin.

Once again thanks for the time , let me know :)

**Comment by rez1dent3** [comment]
I will gladly review your PR

**Comment by nikuscs** [comment]
@rez1dent3  Just a quick update here, after testing seems like the problem is not the Tags itself but the predis composer module instead. Using PHPredis Extension works just fine on Redis 5.X. Iv forked the repo and made a solution without using Tags at all and seems like the increment is not well implemented for Floats. A good alternative would be just setting the key directly instead of using increment. If you can point me on the right direction on how to correctly sum the current balance before setting the cache key ( instead of increment ) would be awesome, since it will save me and maybe other developers some time installing/compiling phpredis.so in local environments.

**Comment by rez1dent3** [comment]
I must have been very tired when I checked the case. Now I decided to double-check and everything works even on redis 3.x+.
PR #6 (add unit)

![Screenshot from 2020-11-19 00-57-45](https://user-images.githubusercontent.com/5111255/99593374-a0bd6500-2a02-11eb-85c2-b463d878e6d7.png)

**Comment by nikuscs** [comment]
That said, seems like the issue is with PRedis so no reason for keep the issue open. Thanks a lot for the time here! Looking forward to contribute.
Ps : open sponsors :)

**Comment by rez1dent3** [comment]
Let's leave the issue open for now. I will try to find a solution to your problem.

I tested with both the `predis/predis` library and the `phpiredis` extension yesterday.

**Comment by rez1dent3** [comment]
@igerslike I approached the problem strategically. Unfortunately, the problem occurs on large amounts. Now I will add data to the lock and increment it to php.
see tag 1.0.1

**Comment by nikuscs** [comment]
@rez1dent3 indeed it was a large amounts, and also i tried to decrease the "math.scale" to 32 to see it helped and decimals to 5. Even tho i was doing some test cases on my end! Thanks a lot ill check the PR right now
